# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9998981722e2b33a7bbea0285c503f3c2b170c62a8fbdb5dbae50a8572ebfb76d384ae9b24543b1be3169a39e0f3abb0aefc7de1ebb3836459f0bf3a49c13b0

test:
  secret_key_base: 7c7019b231d1d91ea18c85cb2d472935efd38e1beb196ee0960201c6a601f1d137f42055934d226b6c26998272ca0bc2ca335c1b2b529948b5287b0d9549174a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
